name: amchart.js
description: A web app that use amchart.js in dart
version: 0.0.1
author: David Zhao <davidyzhao@yahoo.com>

environment:
  sdk: '>=2.0.0-dev < 3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  sass_builder: "^2.1.1"
